// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	cache "suscord/internal/domain/storage/cache"
	database "suscord/internal/domain/storage/database"

	file "suscord/internal/domain/storage/file"

	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Cache provides a mock function with no fields
func (_m *MockStorage) Cache() cache.Storage {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cache")
	}

	var r0 cache.Storage
	if rf, ok := ret.Get(0).(func() cache.Storage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cache.Storage)
		}
	}

	return r0
}

// MockStorage_Cache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cache'
type MockStorage_Cache_Call struct {
	*mock.Call
}

// Cache is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Cache() *MockStorage_Cache_Call {
	return &MockStorage_Cache_Call{Call: _e.mock.On("Cache")}
}

func (_c *MockStorage_Cache_Call) Run(run func()) *MockStorage_Cache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Cache_Call) Return(_a0 cache.Storage) *MockStorage_Cache_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Cache_Call) RunAndReturn(run func() cache.Storage) *MockStorage_Cache_Call {
	_c.Call.Return(run)
	return _c
}

// Database provides a mock function with no fields
func (_m *MockStorage) Database() database.Storage {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Database")
	}

	var r0 database.Storage
	if rf, ok := ret.Get(0).(func() database.Storage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.Storage)
		}
	}

	return r0
}

// MockStorage_Database_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Database'
type MockStorage_Database_Call struct {
	*mock.Call
}

// Database is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Database() *MockStorage_Database_Call {
	return &MockStorage_Database_Call{Call: _e.mock.On("Database")}
}

func (_c *MockStorage_Database_Call) Run(run func()) *MockStorage_Database_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Database_Call) Return(_a0 database.Storage) *MockStorage_Database_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Database_Call) RunAndReturn(run func() database.Storage) *MockStorage_Database_Call {
	_c.Call.Return(run)
	return _c
}

// File provides a mock function with no fields
func (_m *MockStorage) File() file.FileStorage {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for File")
	}

	var r0 file.FileStorage
	if rf, ok := ret.Get(0).(func() file.FileStorage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(file.FileStorage)
		}
	}

	return r0
}

// MockStorage_File_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'File'
type MockStorage_File_Call struct {
	*mock.Call
}

// File is a helper method to define mock.On call
func (_e *MockStorage_Expecter) File() *MockStorage_File_Call {
	return &MockStorage_File_Call{Call: _e.mock.On("File")}
}

func (_c *MockStorage_File_Call) Run(run func()) *MockStorage_File_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_File_Call) Return(_a0 file.FileStorage) *MockStorage_File_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_File_Call) RunAndReturn(run func() file.FileStorage) *MockStorage_File_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
