// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// MockFileService is an autogenerated mock type for the FileService type
type MockFileService struct {
	mock.Mock
}

type MockFileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileService) EXPECT() *MockFileService_Expecter {
	return &MockFileService_Expecter{mock: &_m.Mock}
}

// UploadFile provides a mock function with given fields: file, fileUpload
func (_m *MockFileService) UploadFile(file *multipart.FileHeader, fileUpload ...string) (string, error) {
	_va := make([]interface{}, len(fileUpload))
	for _i := range fileUpload {
		_va[_i] = fileUpload[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, file)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, ...string) (string, error)); ok {
		return rf(file, fileUpload...)
	}
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, ...string) string); ok {
		r0 = rf(file, fileUpload...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*multipart.FileHeader, ...string) error); ok {
		r1 = rf(file, fileUpload...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileService_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type MockFileService_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - file *multipart.FileHeader
//   - fileUpload ...string
func (_e *MockFileService_Expecter) UploadFile(file interface{}, fileUpload ...interface{}) *MockFileService_UploadFile_Call {
	return &MockFileService_UploadFile_Call{Call: _e.mock.On("UploadFile",
		append([]interface{}{file}, fileUpload...)...)}
}

func (_c *MockFileService_UploadFile_Call) Run(run func(file *multipart.FileHeader, fileUpload ...string)) *MockFileService_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(*multipart.FileHeader), variadicArgs...)
	})
	return _c
}

func (_c *MockFileService_UploadFile_Call) Return(_a0 string, _a1 error) *MockFileService_UploadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileService_UploadFile_Call) RunAndReturn(run func(*multipart.FileHeader, ...string) (string, error)) *MockFileService_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileService creates a new instance of MockFileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileService {
	mock := &MockFileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
