// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "suscord/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockChatService is an autogenerated mock type for the ChatService type
type MockChatService struct {
	mock.Mock
}

type MockChatService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatService) EXPECT() *MockChatService_Expecter {
	return &MockChatService_Expecter{mock: &_m.Mock}
}

// CreateGroupChat provides a mock function with given fields: ctx, userID, data
func (_m *MockChatService) CreateGroupChat(ctx context.Context, userID uint, data *entity.CreateGroupChat) (*entity.Chat, error) {
	ret := _m.Called(ctx, userID, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroupChat")
	}

	var r0 *entity.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *entity.CreateGroupChat) (*entity.Chat, error)); ok {
		return rf(ctx, userID, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *entity.CreateGroupChat) *entity.Chat); ok {
		r0 = rf(ctx, userID, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *entity.CreateGroupChat) error); ok {
		r1 = rf(ctx, userID, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatService_CreateGroupChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroupChat'
type MockChatService_CreateGroupChat_Call struct {
	*mock.Call
}

// CreateGroupChat is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - data *entity.CreateGroupChat
func (_e *MockChatService_Expecter) CreateGroupChat(ctx interface{}, userID interface{}, data interface{}) *MockChatService_CreateGroupChat_Call {
	return &MockChatService_CreateGroupChat_Call{Call: _e.mock.On("CreateGroupChat", ctx, userID, data)}
}

func (_c *MockChatService_CreateGroupChat_Call) Run(run func(ctx context.Context, userID uint, data *entity.CreateGroupChat)) *MockChatService_CreateGroupChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*entity.CreateGroupChat))
	})
	return _c
}

func (_c *MockChatService_CreateGroupChat_Call) Return(_a0 *entity.Chat, _a1 error) *MockChatService_CreateGroupChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatService_CreateGroupChat_Call) RunAndReturn(run func(context.Context, uint, *entity.CreateGroupChat) (*entity.Chat, error)) *MockChatService_CreateGroupChat_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePrivateChat provides a mock function with given fields: ctx, userID, chatID
func (_m *MockChatService) DeletePrivateChat(ctx context.Context, userID uint, chatID uint) error {
	ret := _m.Called(ctx, userID, chatID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePrivateChat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, userID, chatID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatService_DeletePrivateChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePrivateChat'
type MockChatService_DeletePrivateChat_Call struct {
	*mock.Call
}

// DeletePrivateChat is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - chatID uint
func (_e *MockChatService_Expecter) DeletePrivateChat(ctx interface{}, userID interface{}, chatID interface{}) *MockChatService_DeletePrivateChat_Call {
	return &MockChatService_DeletePrivateChat_Call{Call: _e.mock.On("DeletePrivateChat", ctx, userID, chatID)}
}

func (_c *MockChatService_DeletePrivateChat_Call) Run(run func(ctx context.Context, userID uint, chatID uint)) *MockChatService_DeletePrivateChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockChatService_DeletePrivateChat_Call) Return(_a0 error) *MockChatService_DeletePrivateChat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatService_DeletePrivateChat_Call) RunAndReturn(run func(context.Context, uint, uint) error) *MockChatService_DeletePrivateChat_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreatePrivateChat provides a mock function with given fields: ctx, data
func (_m *MockChatService) GetOrCreatePrivateChat(ctx context.Context, data *entity.CreatePrivateChat) (*entity.Chat, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreatePrivateChat")
	}

	var r0 *entity.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.CreatePrivateChat) (*entity.Chat, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.CreatePrivateChat) *entity.Chat); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.CreatePrivateChat) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatService_GetOrCreatePrivateChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreatePrivateChat'
type MockChatService_GetOrCreatePrivateChat_Call struct {
	*mock.Call
}

// GetOrCreatePrivateChat is a helper method to define mock.On call
//   - ctx context.Context
//   - data *entity.CreatePrivateChat
func (_e *MockChatService_Expecter) GetOrCreatePrivateChat(ctx interface{}, data interface{}) *MockChatService_GetOrCreatePrivateChat_Call {
	return &MockChatService_GetOrCreatePrivateChat_Call{Call: _e.mock.On("GetOrCreatePrivateChat", ctx, data)}
}

func (_c *MockChatService_GetOrCreatePrivateChat_Call) Run(run func(ctx context.Context, data *entity.CreatePrivateChat)) *MockChatService_GetOrCreatePrivateChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.CreatePrivateChat))
	})
	return _c
}

func (_c *MockChatService_GetOrCreatePrivateChat_Call) Return(_a0 *entity.Chat, _a1 error) *MockChatService_GetOrCreatePrivateChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatService_GetOrCreatePrivateChat_Call) RunAndReturn(run func(context.Context, *entity.CreatePrivateChat) (*entity.Chat, error)) *MockChatService_GetOrCreatePrivateChat_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserChats provides a mock function with given fields: ctx, userID, searchPattern
func (_m *MockChatService) GetUserChats(ctx context.Context, userID uint, searchPattern string) ([]*entity.Chat, error) {
	ret := _m.Called(ctx, userID, searchPattern)

	if len(ret) == 0 {
		panic("no return value specified for GetUserChats")
	}

	var r0 []*entity.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) ([]*entity.Chat, error)); ok {
		return rf(ctx, userID, searchPattern)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) []*entity.Chat); ok {
		r0 = rf(ctx, userID, searchPattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = rf(ctx, userID, searchPattern)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatService_GetUserChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserChats'
type MockChatService_GetUserChats_Call struct {
	*mock.Call
}

// GetUserChats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - searchPattern string
func (_e *MockChatService_Expecter) GetUserChats(ctx interface{}, userID interface{}, searchPattern interface{}) *MockChatService_GetUserChats_Call {
	return &MockChatService_GetUserChats_Call{Call: _e.mock.On("GetUserChats", ctx, userID, searchPattern)}
}

func (_c *MockChatService_GetUserChats_Call) Run(run func(ctx context.Context, userID uint, searchPattern string)) *MockChatService_GetUserChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *MockChatService_GetUserChats_Call) Return(_a0 []*entity.Chat, _a1 error) *MockChatService_GetUserChats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatService_GetUserChats_Call) RunAndReturn(run func(context.Context, uint, string) ([]*entity.Chat, error)) *MockChatService_GetUserChats_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroupChat provides a mock function with given fields: ctx, userID, chatID, data
func (_m *MockChatService) UpdateGroupChat(ctx context.Context, userID uint, chatID uint, data *entity.UpdateChat) (*entity.Chat, error) {
	ret := _m.Called(ctx, userID, chatID, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroupChat")
	}

	var r0 *entity.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *entity.UpdateChat) (*entity.Chat, error)); ok {
		return rf(ctx, userID, chatID, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *entity.UpdateChat) *entity.Chat); ok {
		r0 = rf(ctx, userID, chatID, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, *entity.UpdateChat) error); ok {
		r1 = rf(ctx, userID, chatID, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatService_UpdateGroupChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroupChat'
type MockChatService_UpdateGroupChat_Call struct {
	*mock.Call
}

// UpdateGroupChat is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - chatID uint
//   - data *entity.UpdateChat
func (_e *MockChatService_Expecter) UpdateGroupChat(ctx interface{}, userID interface{}, chatID interface{}, data interface{}) *MockChatService_UpdateGroupChat_Call {
	return &MockChatService_UpdateGroupChat_Call{Call: _e.mock.On("UpdateGroupChat", ctx, userID, chatID, data)}
}

func (_c *MockChatService_UpdateGroupChat_Call) Run(run func(ctx context.Context, userID uint, chatID uint, data *entity.UpdateChat)) *MockChatService_UpdateGroupChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(*entity.UpdateChat))
	})
	return _c
}

func (_c *MockChatService_UpdateGroupChat_Call) Return(_a0 *entity.Chat, _a1 error) *MockChatService_UpdateGroupChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatService_UpdateGroupChat_Call) RunAndReturn(run func(context.Context, uint, uint, *entity.UpdateChat) (*entity.Chat, error)) *MockChatService_UpdateGroupChat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatService creates a new instance of MockChatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatService {
	mock := &MockChatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
