// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAttachementService is an autogenerated mock type for the AttachementService type
type MockAttachementService struct {
	mock.Mock
}

type MockAttachementService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttachementService) EXPECT() *MockAttachementService_Expecter {
	return &MockAttachementService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, userID, attachmentID
func (_m *MockAttachementService) Delete(ctx context.Context, userID uint, attachmentID uint) error {
	ret := _m.Called(ctx, userID, attachmentID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, userID, attachmentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAttachementService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAttachementService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - attachmentID uint
func (_e *MockAttachementService_Expecter) Delete(ctx interface{}, userID interface{}, attachmentID interface{}) *MockAttachementService_Delete_Call {
	return &MockAttachementService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, attachmentID)}
}

func (_c *MockAttachementService_Delete_Call) Run(run func(ctx context.Context, userID uint, attachmentID uint)) *MockAttachementService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockAttachementService_Delete_Call) Return(_a0 error) *MockAttachementService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAttachementService_Delete_Call) RunAndReturn(run func(context.Context, uint, uint) error) *MockAttachementService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAttachementService creates a new instance of MockAttachementService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttachementService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttachementService {
	mock := &MockAttachementService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
