// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	service "suscord/internal/domain/service"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Attachment provides a mock function with no fields
func (_m *MockService) Attachment() service.AttachementService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Attachment")
	}

	var r0 service.AttachementService
	if rf, ok := ret.Get(0).(func() service.AttachementService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.AttachementService)
		}
	}

	return r0
}

// MockService_Attachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attachment'
type MockService_Attachment_Call struct {
	*mock.Call
}

// Attachment is a helper method to define mock.On call
func (_e *MockService_Expecter) Attachment() *MockService_Attachment_Call {
	return &MockService_Attachment_Call{Call: _e.mock.On("Attachment")}
}

func (_c *MockService_Attachment_Call) Run(run func()) *MockService_Attachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Attachment_Call) Return(_a0 service.AttachementService) *MockService_Attachment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Attachment_Call) RunAndReturn(run func() service.AttachementService) *MockService_Attachment_Call {
	_c.Call.Return(run)
	return _c
}

// Auth provides a mock function with no fields
func (_m *MockService) Auth() service.AuthService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 service.AuthService
	if rf, ok := ret.Get(0).(func() service.AuthService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.AuthService)
		}
	}

	return r0
}

// MockService_Auth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Auth'
type MockService_Auth_Call struct {
	*mock.Call
}

// Auth is a helper method to define mock.On call
func (_e *MockService_Expecter) Auth() *MockService_Auth_Call {
	return &MockService_Auth_Call{Call: _e.mock.On("Auth")}
}

func (_c *MockService_Auth_Call) Run(run func()) *MockService_Auth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Auth_Call) Return(_a0 service.AuthService) *MockService_Auth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Auth_Call) RunAndReturn(run func() service.AuthService) *MockService_Auth_Call {
	_c.Call.Return(run)
	return _c
}

// Chat provides a mock function with no fields
func (_m *MockService) Chat() service.ChatService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 service.ChatService
	if rf, ok := ret.Get(0).(func() service.ChatService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.ChatService)
		}
	}

	return r0
}

// MockService_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockService_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
func (_e *MockService_Expecter) Chat() *MockService_Chat_Call {
	return &MockService_Chat_Call{Call: _e.mock.On("Chat")}
}

func (_c *MockService_Chat_Call) Run(run func()) *MockService_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Chat_Call) Return(_a0 service.ChatService) *MockService_Chat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Chat_Call) RunAndReturn(run func() service.ChatService) *MockService_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// ChatMember provides a mock function with no fields
func (_m *MockService) ChatMember() service.ChatMemberService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChatMember")
	}

	var r0 service.ChatMemberService
	if rf, ok := ret.Get(0).(func() service.ChatMemberService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.ChatMemberService)
		}
	}

	return r0
}

// MockService_ChatMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatMember'
type MockService_ChatMember_Call struct {
	*mock.Call
}

// ChatMember is a helper method to define mock.On call
func (_e *MockService_Expecter) ChatMember() *MockService_ChatMember_Call {
	return &MockService_ChatMember_Call{Call: _e.mock.On("ChatMember")}
}

func (_c *MockService_ChatMember_Call) Run(run func()) *MockService_ChatMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_ChatMember_Call) Return(_a0 service.ChatMemberService) *MockService_ChatMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ChatMember_Call) RunAndReturn(run func() service.ChatMemberService) *MockService_ChatMember_Call {
	_c.Call.Return(run)
	return _c
}

// File provides a mock function with no fields
func (_m *MockService) File() service.FileService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for File")
	}

	var r0 service.FileService
	if rf, ok := ret.Get(0).(func() service.FileService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.FileService)
		}
	}

	return r0
}

// MockService_File_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'File'
type MockService_File_Call struct {
	*mock.Call
}

// File is a helper method to define mock.On call
func (_e *MockService_Expecter) File() *MockService_File_Call {
	return &MockService_File_Call{Call: _e.mock.On("File")}
}

func (_c *MockService_File_Call) Run(run func()) *MockService_File_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_File_Call) Return(_a0 service.FileService) *MockService_File_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_File_Call) RunAndReturn(run func() service.FileService) *MockService_File_Call {
	_c.Call.Return(run)
	return _c
}

// Message provides a mock function with no fields
func (_m *MockService) Message() service.MessageService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 service.MessageService
	if rf, ok := ret.Get(0).(func() service.MessageService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.MessageService)
		}
	}

	return r0
}

// MockService_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type MockService_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
func (_e *MockService_Expecter) Message() *MockService_Message_Call {
	return &MockService_Message_Call{Call: _e.mock.On("Message")}
}

func (_c *MockService_Message_Call) Run(run func()) *MockService_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Message_Call) Return(_a0 service.MessageService) *MockService_Message_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Message_Call) RunAndReturn(run func() service.MessageService) *MockService_Message_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function with no fields
func (_m *MockService) User() service.UserService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 service.UserService
	if rf, ok := ret.Get(0).(func() service.UserService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.UserService)
		}
	}

	return r0
}

// MockService_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type MockService_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
func (_e *MockService_Expecter) User() *MockService_User_Call {
	return &MockService_User_Call{Call: _e.mock.On("User")}
}

func (_c *MockService_User_Call) Run(run func()) *MockService_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_User_Call) Return(_a0 service.UserService) *MockService_User_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_User_Call) RunAndReturn(run func() service.UserService) *MockService_User_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
