// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "suscord/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// MockMessageService is an autogenerated mock type for the MessageService type
type MockMessageService struct {
	mock.Mock
}

type MockMessageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageService) EXPECT() *MockMessageService_Expecter {
	return &MockMessageService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, chatID, data, files
func (_m *MockMessageService) Create(ctx context.Context, userID uint, chatID uint, data *entity.CreateMessage, files []*multipart.FileHeader) (*entity.Message, error) {
	ret := _m.Called(ctx, userID, chatID, data, files)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *entity.CreateMessage, []*multipart.FileHeader) (*entity.Message, error)); ok {
		return rf(ctx, userID, chatID, data, files)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *entity.CreateMessage, []*multipart.FileHeader) *entity.Message); ok {
		r0 = rf(ctx, userID, chatID, data, files)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, *entity.CreateMessage, []*multipart.FileHeader) error); ok {
		r1 = rf(ctx, userID, chatID, data, files)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMessageService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - chatID uint
//   - data *entity.CreateMessage
//   - files []*multipart.FileHeader
func (_e *MockMessageService_Expecter) Create(ctx interface{}, userID interface{}, chatID interface{}, data interface{}, files interface{}) *MockMessageService_Create_Call {
	return &MockMessageService_Create_Call{Call: _e.mock.On("Create", ctx, userID, chatID, data, files)}
}

func (_c *MockMessageService_Create_Call) Run(run func(ctx context.Context, userID uint, chatID uint, data *entity.CreateMessage, files []*multipart.FileHeader)) *MockMessageService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(*entity.CreateMessage), args[4].([]*multipart.FileHeader))
	})
	return _c
}

func (_c *MockMessageService_Create_Call) Return(_a0 *entity.Message, _a1 error) *MockMessageService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageService_Create_Call) RunAndReturn(run func(context.Context, uint, uint, *entity.CreateMessage, []*multipart.FileHeader) (*entity.Message, error)) *MockMessageService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, messageID
func (_m *MockMessageService) Delete(ctx context.Context, userID uint, messageID uint) error {
	ret := _m.Called(ctx, userID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, userID, messageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMessageService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - messageID uint
func (_e *MockMessageService_Expecter) Delete(ctx interface{}, userID interface{}, messageID interface{}) *MockMessageService_Delete_Call {
	return &MockMessageService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, messageID)}
}

func (_c *MockMessageService_Delete_Call) Run(run func(ctx context.Context, userID uint, messageID uint)) *MockMessageService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockMessageService_Delete_Call) Return(_a0 error) *MockMessageService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageService_Delete_Call) RunAndReturn(run func(context.Context, uint, uint) error) *MockMessageService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatMessages provides a mock function with given fields: ctx, input
func (_m *MockMessageService) GetChatMessages(ctx context.Context, input *entity.GetMessagesInput) ([]*entity.Message, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetChatMessages")
	}

	var r0 []*entity.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.GetMessagesInput) ([]*entity.Message, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.GetMessagesInput) []*entity.Message); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.GetMessagesInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageService_GetChatMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatMessages'
type MockMessageService_GetChatMessages_Call struct {
	*mock.Call
}

// GetChatMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - input *entity.GetMessagesInput
func (_e *MockMessageService_Expecter) GetChatMessages(ctx interface{}, input interface{}) *MockMessageService_GetChatMessages_Call {
	return &MockMessageService_GetChatMessages_Call{Call: _e.mock.On("GetChatMessages", ctx, input)}
}

func (_c *MockMessageService_GetChatMessages_Call) Run(run func(ctx context.Context, input *entity.GetMessagesInput)) *MockMessageService_GetChatMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.GetMessagesInput))
	})
	return _c
}

func (_c *MockMessageService_GetChatMessages_Call) Return(_a0 []*entity.Message, _a1 error) *MockMessageService_GetChatMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageService_GetChatMessages_Call) RunAndReturn(run func(context.Context, *entity.GetMessagesInput) ([]*entity.Message, error)) *MockMessageService_GetChatMessages_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, messageID, data
func (_m *MockMessageService) Update(ctx context.Context, userID uint, messageID uint, data *entity.UpdateMessage) (*entity.Message, error) {
	ret := _m.Called(ctx, userID, messageID, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *entity.UpdateMessage) (*entity.Message, error)); ok {
		return rf(ctx, userID, messageID, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *entity.UpdateMessage) *entity.Message); ok {
		r0 = rf(ctx, userID, messageID, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, *entity.UpdateMessage) error); ok {
		r1 = rf(ctx, userID, messageID, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMessageService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - messageID uint
//   - data *entity.UpdateMessage
func (_e *MockMessageService_Expecter) Update(ctx interface{}, userID interface{}, messageID interface{}, data interface{}) *MockMessageService_Update_Call {
	return &MockMessageService_Update_Call{Call: _e.mock.On("Update", ctx, userID, messageID, data)}
}

func (_c *MockMessageService_Update_Call) Run(run func(ctx context.Context, userID uint, messageID uint, data *entity.UpdateMessage)) *MockMessageService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(*entity.UpdateMessage))
	})
	return _c
}

func (_c *MockMessageService_Update_Call) Return(_a0 *entity.Message, _a1 error) *MockMessageService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageService_Update_Call) RunAndReturn(run func(context.Context, uint, uint, *entity.UpdateMessage) (*entity.Message, error)) *MockMessageService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageService creates a new instance of MockMessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageService {
	mock := &MockMessageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
