// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "suscord/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockChatMemberService is an autogenerated mock type for the ChatMemberService type
type MockChatMemberService struct {
	mock.Mock
}

type MockChatMemberService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatMemberService) EXPECT() *MockChatMemberService_Expecter {
	return &MockChatMemberService_Expecter{mock: &_m.Mock}
}

// AcceptInvite provides a mock function with given fields: ctx, userID, code
func (_m *MockChatMemberService) AcceptInvite(ctx context.Context, userID uint, code string) error {
	ret := _m.Called(ctx, userID, code)

	if len(ret) == 0 {
		panic("no return value specified for AcceptInvite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, userID, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatMemberService_AcceptInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptInvite'
type MockChatMemberService_AcceptInvite_Call struct {
	*mock.Call
}

// AcceptInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - code string
func (_e *MockChatMemberService_Expecter) AcceptInvite(ctx interface{}, userID interface{}, code interface{}) *MockChatMemberService_AcceptInvite_Call {
	return &MockChatMemberService_AcceptInvite_Call{Call: _e.mock.On("AcceptInvite", ctx, userID, code)}
}

func (_c *MockChatMemberService_AcceptInvite_Call) Run(run func(ctx context.Context, userID uint, code string)) *MockChatMemberService_AcceptInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *MockChatMemberService_AcceptInvite_Call) Return(_a0 error) *MockChatMemberService_AcceptInvite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatMemberService_AcceptInvite_Call) RunAndReturn(run func(context.Context, uint, string) error) *MockChatMemberService_AcceptInvite_Call {
	_c.Call.Return(run)
	return _c
}

// GetNonMembers provides a mock function with given fields: ctx, chatID, memberID
func (_m *MockChatMemberService) GetNonMembers(ctx context.Context, chatID uint, memberID uint) ([]*entity.User, error) {
	ret := _m.Called(ctx, chatID, memberID)

	if len(ret) == 0 {
		panic("no return value specified for GetNonMembers")
	}

	var r0 []*entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) ([]*entity.User, error)); ok {
		return rf(ctx, chatID, memberID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) []*entity.User); ok {
		r0 = rf(ctx, chatID, memberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, chatID, memberID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatMemberService_GetNonMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNonMembers'
type MockChatMemberService_GetNonMembers_Call struct {
	*mock.Call
}

// GetNonMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uint
//   - memberID uint
func (_e *MockChatMemberService_Expecter) GetNonMembers(ctx interface{}, chatID interface{}, memberID interface{}) *MockChatMemberService_GetNonMembers_Call {
	return &MockChatMemberService_GetNonMembers_Call{Call: _e.mock.On("GetNonMembers", ctx, chatID, memberID)}
}

func (_c *MockChatMemberService_GetNonMembers_Call) Run(run func(ctx context.Context, chatID uint, memberID uint)) *MockChatMemberService_GetNonMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockChatMemberService_GetNonMembers_Call) Return(_a0 []*entity.User, _a1 error) *MockChatMemberService_GetNonMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatMemberService_GetNonMembers_Call) RunAndReturn(run func(context.Context, uint, uint) ([]*entity.User, error)) *MockChatMemberService_GetNonMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotChatMembers provides a mock function with given fields: ctx, chatID, memberID
func (_m *MockChatMemberService) GetNotChatMembers(ctx context.Context, chatID uint, memberID uint) ([]*entity.User, error) {
	ret := _m.Called(ctx, chatID, memberID)

	if len(ret) == 0 {
		panic("no return value specified for GetNotChatMembers")
	}

	var r0 []*entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) ([]*entity.User, error)); ok {
		return rf(ctx, chatID, memberID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) []*entity.User); ok {
		r0 = rf(ctx, chatID, memberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, chatID, memberID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatMemberService_GetNotChatMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotChatMembers'
type MockChatMemberService_GetNotChatMembers_Call struct {
	*mock.Call
}

// GetNotChatMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uint
//   - memberID uint
func (_e *MockChatMemberService_Expecter) GetNotChatMembers(ctx interface{}, chatID interface{}, memberID interface{}) *MockChatMemberService_GetNotChatMembers_Call {
	return &MockChatMemberService_GetNotChatMembers_Call{Call: _e.mock.On("GetNotChatMembers", ctx, chatID, memberID)}
}

func (_c *MockChatMemberService_GetNotChatMembers_Call) Run(run func(ctx context.Context, chatID uint, memberID uint)) *MockChatMemberService_GetNotChatMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockChatMemberService_GetNotChatMembers_Call) Return(_a0 []*entity.User, _a1 error) *MockChatMemberService_GetNotChatMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatMemberService_GetNotChatMembers_Call) RunAndReturn(run func(context.Context, uint, uint) ([]*entity.User, error)) *MockChatMemberService_GetNotChatMembers_Call {
	_c.Call.Return(run)
	return _c
}

// IsMemberOfChat provides a mock function with given fields: ctx, userID, chatID
func (_m *MockChatMemberService) IsMemberOfChat(ctx context.Context, userID uint, chatID uint) (bool, error) {
	ret := _m.Called(ctx, userID, chatID)

	if len(ret) == 0 {
		panic("no return value specified for IsMemberOfChat")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (bool, error)); ok {
		return rf(ctx, userID, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) bool); ok {
		r0 = rf(ctx, userID, chatID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, userID, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatMemberService_IsMemberOfChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMemberOfChat'
type MockChatMemberService_IsMemberOfChat_Call struct {
	*mock.Call
}

// IsMemberOfChat is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - chatID uint
func (_e *MockChatMemberService_Expecter) IsMemberOfChat(ctx interface{}, userID interface{}, chatID interface{}) *MockChatMemberService_IsMemberOfChat_Call {
	return &MockChatMemberService_IsMemberOfChat_Call{Call: _e.mock.On("IsMemberOfChat", ctx, userID, chatID)}
}

func (_c *MockChatMemberService_IsMemberOfChat_Call) Run(run func(ctx context.Context, userID uint, chatID uint)) *MockChatMemberService_IsMemberOfChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockChatMemberService_IsMemberOfChat_Call) Return(_a0 bool, _a1 error) *MockChatMemberService_IsMemberOfChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatMemberService_IsMemberOfChat_Call) RunAndReturn(run func(context.Context, uint, uint) (bool, error)) *MockChatMemberService_IsMemberOfChat_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveFromChat provides a mock function with given fields: ctx, chatID, userID
func (_m *MockChatMemberService) LeaveFromChat(ctx context.Context, chatID uint, userID uint) error {
	ret := _m.Called(ctx, chatID, userID)

	if len(ret) == 0 {
		panic("no return value specified for LeaveFromChat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, chatID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatMemberService_LeaveFromChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveFromChat'
type MockChatMemberService_LeaveFromChat_Call struct {
	*mock.Call
}

// LeaveFromChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uint
//   - userID uint
func (_e *MockChatMemberService_Expecter) LeaveFromChat(ctx interface{}, chatID interface{}, userID interface{}) *MockChatMemberService_LeaveFromChat_Call {
	return &MockChatMemberService_LeaveFromChat_Call{Call: _e.mock.On("LeaveFromChat", ctx, chatID, userID)}
}

func (_c *MockChatMemberService_LeaveFromChat_Call) Run(run func(ctx context.Context, chatID uint, userID uint)) *MockChatMemberService_LeaveFromChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockChatMemberService_LeaveFromChat_Call) Return(_a0 error) *MockChatMemberService_LeaveFromChat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatMemberService_LeaveFromChat_Call) RunAndReturn(run func(context.Context, uint, uint) error) *MockChatMemberService_LeaveFromChat_Call {
	_c.Call.Return(run)
	return _c
}

// SendInvite provides a mock function with given fields: ctx, ownerID, chatID, userID
func (_m *MockChatMemberService) SendInvite(ctx context.Context, ownerID uint, chatID uint, userID uint) error {
	ret := _m.Called(ctx, ownerID, chatID, userID)

	if len(ret) == 0 {
		panic("no return value specified for SendInvite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, uint) error); ok {
		r0 = rf(ctx, ownerID, chatID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatMemberService_SendInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendInvite'
type MockChatMemberService_SendInvite_Call struct {
	*mock.Call
}

// SendInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uint
//   - chatID uint
//   - userID uint
func (_e *MockChatMemberService_Expecter) SendInvite(ctx interface{}, ownerID interface{}, chatID interface{}, userID interface{}) *MockChatMemberService_SendInvite_Call {
	return &MockChatMemberService_SendInvite_Call{Call: _e.mock.On("SendInvite", ctx, ownerID, chatID, userID)}
}

func (_c *MockChatMemberService_SendInvite_Call) Run(run func(ctx context.Context, ownerID uint, chatID uint, userID uint)) *MockChatMemberService_SendInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(uint))
	})
	return _c
}

func (_c *MockChatMemberService_SendInvite_Call) Return(_a0 error) *MockChatMemberService_SendInvite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatMemberService_SendInvite_Call) RunAndReturn(run func(context.Context, uint, uint, uint) error) *MockChatMemberService_SendInvite_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatMemberService creates a new instance of MockChatMemberService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatMemberService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatMemberService {
	mock := &MockChatMemberService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
