// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "suscord/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, userID
func (_m *MockUserService) GetByID(ctx context.Context, userID uint) (*entity.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockUserService_Expecter) GetByID(ctx interface{}, userID interface{}) *MockUserService_GetByID_Call {
	return &MockUserService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID)}
}

func (_c *MockUserService_GetByID_Call) Run(run func(ctx context.Context, userID uint)) *MockUserService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockUserService_GetByID_Call) Return(_a0 *entity.User, _a1 error) *MockUserService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.User, error)) *MockUserService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: ctx, userID, username
func (_m *MockUserService) SearchUsers(ctx context.Context, userID uint, username string) ([]*entity.User, error) {
	ret := _m.Called(ctx, userID, username)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []*entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) ([]*entity.User, error)); ok {
		return rf(ctx, userID, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) []*entity.User); ok {
		r0 = rf(ctx, userID, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = rf(ctx, userID, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockUserService_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - username string
func (_e *MockUserService_Expecter) SearchUsers(ctx interface{}, userID interface{}, username interface{}) *MockUserService_SearchUsers_Call {
	return &MockUserService_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, userID, username)}
}

func (_c *MockUserService_SearchUsers_Call) Run(run func(ctx context.Context, userID uint, username string)) *MockUserService_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_SearchUsers_Call) Return(_a0 []*entity.User, _a1 error) *MockUserService_SearchUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_SearchUsers_Call) RunAndReturn(run func(context.Context, uint, string) ([]*entity.User, error)) *MockUserService_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
