// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// MockFileStorage is an autogenerated mock type for the FileStorage type
type MockFileStorage struct {
	mock.Mock
}

type MockFileStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileStorage) EXPECT() *MockFileStorage_Expecter {
	return &MockFileStorage_Expecter{mock: &_m.Mock}
}

// UploadFile provides a mock function with given fields: _a0, uploadTo
func (_m *MockFileStorage) UploadFile(_a0 *multipart.FileHeader, uploadTo ...string) (string, error) {
	_va := make([]interface{}, len(uploadTo))
	for _i := range uploadTo {
		_va[_i] = uploadTo[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, ...string) (string, error)); ok {
		return rf(_a0, uploadTo...)
	}
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, ...string) string); ok {
		r0 = rf(_a0, uploadTo...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*multipart.FileHeader, ...string) error); ok {
		r1 = rf(_a0, uploadTo...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileStorage_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type MockFileStorage_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - _a0 *multipart.FileHeader
//   - uploadTo ...string
func (_e *MockFileStorage_Expecter) UploadFile(_a0 interface{}, uploadTo ...interface{}) *MockFileStorage_UploadFile_Call {
	return &MockFileStorage_UploadFile_Call{Call: _e.mock.On("UploadFile",
		append([]interface{}{_a0}, uploadTo...)...)}
}

func (_c *MockFileStorage_UploadFile_Call) Run(run func(_a0 *multipart.FileHeader, uploadTo ...string)) *MockFileStorage_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(*multipart.FileHeader), variadicArgs...)
	})
	return _c
}

func (_c *MockFileStorage_UploadFile_Call) Return(_a0 string, _a1 error) *MockFileStorage_UploadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileStorage_UploadFile_Call) RunAndReturn(run func(*multipart.FileHeader, ...string) (string, error)) *MockFileStorage_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileStorage creates a new instance of MockFileStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileStorage {
	mock := &MockFileStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
