// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "suscord/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockMessageStorage is an autogenerated mock type for the MessageStorage type
type MockMessageStorage struct {
	mock.Mock
}

type MockMessageStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageStorage) EXPECT() *MockMessageStorage_Expecter {
	return &MockMessageStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, chatID, data
func (_m *MockMessageStorage) Create(ctx context.Context, userID uint, chatID uint, data *entity.CreateMessage) (uint, error) {
	ret := _m.Called(ctx, userID, chatID, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *entity.CreateMessage) (uint, error)); ok {
		return rf(ctx, userID, chatID, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *entity.CreateMessage) uint); ok {
		r0 = rf(ctx, userID, chatID, data)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, *entity.CreateMessage) error); ok {
		r1 = rf(ctx, userID, chatID, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMessageStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - chatID uint
//   - data *entity.CreateMessage
func (_e *MockMessageStorage_Expecter) Create(ctx interface{}, userID interface{}, chatID interface{}, data interface{}) *MockMessageStorage_Create_Call {
	return &MockMessageStorage_Create_Call{Call: _e.mock.On("Create", ctx, userID, chatID, data)}
}

func (_c *MockMessageStorage_Create_Call) Run(run func(ctx context.Context, userID uint, chatID uint, data *entity.CreateMessage)) *MockMessageStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(*entity.CreateMessage))
	})
	return _c
}

func (_c *MockMessageStorage_Create_Call) Return(_a0 uint, _a1 error) *MockMessageStorage_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageStorage_Create_Call) RunAndReturn(run func(context.Context, uint, uint, *entity.CreateMessage) (uint, error)) *MockMessageStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, messageID
func (_m *MockMessageStorage) Delete(ctx context.Context, messageID uint) error {
	ret := _m.Called(ctx, messageID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, messageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMessageStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID uint
func (_e *MockMessageStorage_Expecter) Delete(ctx interface{}, messageID interface{}) *MockMessageStorage_Delete_Call {
	return &MockMessageStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, messageID)}
}

func (_c *MockMessageStorage_Delete_Call) Run(run func(ctx context.Context, messageID uint)) *MockMessageStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockMessageStorage_Delete_Call) Return(_a0 error) *MockMessageStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageStorage_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockMessageStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByAttachmentID provides a mock function with given fields: ctx, attachmentID
func (_m *MockMessageStorage) GetByAttachmentID(ctx context.Context, attachmentID uint) (*entity.Message, error) {
	ret := _m.Called(ctx, attachmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByAttachmentID")
	}

	var r0 *entity.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Message, error)); ok {
		return rf(ctx, attachmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Message); ok {
		r0 = rf(ctx, attachmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, attachmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageStorage_GetByAttachmentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAttachmentID'
type MockMessageStorage_GetByAttachmentID_Call struct {
	*mock.Call
}

// GetByAttachmentID is a helper method to define mock.On call
//   - ctx context.Context
//   - attachmentID uint
func (_e *MockMessageStorage_Expecter) GetByAttachmentID(ctx interface{}, attachmentID interface{}) *MockMessageStorage_GetByAttachmentID_Call {
	return &MockMessageStorage_GetByAttachmentID_Call{Call: _e.mock.On("GetByAttachmentID", ctx, attachmentID)}
}

func (_c *MockMessageStorage_GetByAttachmentID_Call) Run(run func(ctx context.Context, attachmentID uint)) *MockMessageStorage_GetByAttachmentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockMessageStorage_GetByAttachmentID_Call) Return(_a0 *entity.Message, _a1 error) *MockMessageStorage_GetByAttachmentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageStorage_GetByAttachmentID_Call) RunAndReturn(run func(context.Context, uint) (*entity.Message, error)) *MockMessageStorage_GetByAttachmentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, messageID
func (_m *MockMessageStorage) GetByID(ctx context.Context, messageID uint) (*entity.Message, error) {
	ret := _m.Called(ctx, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Message, error)); ok {
		return rf(ctx, messageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Message); ok {
		r0 = rf(ctx, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, messageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageStorage_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockMessageStorage_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID uint
func (_e *MockMessageStorage_Expecter) GetByID(ctx interface{}, messageID interface{}) *MockMessageStorage_GetByID_Call {
	return &MockMessageStorage_GetByID_Call{Call: _e.mock.On("GetByID", ctx, messageID)}
}

func (_c *MockMessageStorage_GetByID_Call) Run(run func(ctx context.Context, messageID uint)) *MockMessageStorage_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockMessageStorage_GetByID_Call) Return(_a0 *entity.Message, _a1 error) *MockMessageStorage_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageStorage_GetByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.Message, error)) *MockMessageStorage_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function with given fields: ctx, chatID, lastMessageID, limit
func (_m *MockMessageStorage) GetMessages(ctx context.Context, chatID uint, lastMessageID uint, limit int) ([]*entity.Message, error) {
	ret := _m.Called(ctx, chatID, lastMessageID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []*entity.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, int) ([]*entity.Message, error)); ok {
		return rf(ctx, chatID, lastMessageID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, int) []*entity.Message); ok {
		r0 = rf(ctx, chatID, lastMessageID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, int) error); ok {
		r1 = rf(ctx, chatID, lastMessageID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageStorage_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MockMessageStorage_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uint
//   - lastMessageID uint
//   - limit int
func (_e *MockMessageStorage_Expecter) GetMessages(ctx interface{}, chatID interface{}, lastMessageID interface{}, limit interface{}) *MockMessageStorage_GetMessages_Call {
	return &MockMessageStorage_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx, chatID, lastMessageID, limit)}
}

func (_c *MockMessageStorage_GetMessages_Call) Run(run func(ctx context.Context, chatID uint, lastMessageID uint, limit int)) *MockMessageStorage_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(int))
	})
	return _c
}

func (_c *MockMessageStorage_GetMessages_Call) Return(_a0 []*entity.Message, _a1 error) *MockMessageStorage_GetMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageStorage_GetMessages_Call) RunAndReturn(run func(context.Context, uint, uint, int) ([]*entity.Message, error)) *MockMessageStorage_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// IsOwner provides a mock function with given fields: ctx, userID, messageID
func (_m *MockMessageStorage) IsOwner(ctx context.Context, userID uint, messageID uint) (bool, error) {
	ret := _m.Called(ctx, userID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for IsOwner")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (bool, error)); ok {
		return rf(ctx, userID, messageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) bool); ok {
		r0 = rf(ctx, userID, messageID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, userID, messageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageStorage_IsOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOwner'
type MockMessageStorage_IsOwner_Call struct {
	*mock.Call
}

// IsOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - messageID uint
func (_e *MockMessageStorage_Expecter) IsOwner(ctx interface{}, userID interface{}, messageID interface{}) *MockMessageStorage_IsOwner_Call {
	return &MockMessageStorage_IsOwner_Call{Call: _e.mock.On("IsOwner", ctx, userID, messageID)}
}

func (_c *MockMessageStorage_IsOwner_Call) Run(run func(ctx context.Context, userID uint, messageID uint)) *MockMessageStorage_IsOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockMessageStorage_IsOwner_Call) Return(_a0 bool, _a1 error) *MockMessageStorage_IsOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageStorage_IsOwner_Call) RunAndReturn(run func(context.Context, uint, uint) (bool, error)) *MockMessageStorage_IsOwner_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, messageID, data
func (_m *MockMessageStorage) Update(ctx context.Context, messageID uint, data *entity.UpdateMessage) error {
	ret := _m.Called(ctx, messageID, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *entity.UpdateMessage) error); ok {
		r0 = rf(ctx, messageID, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageStorage_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMessageStorage_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID uint
//   - data *entity.UpdateMessage
func (_e *MockMessageStorage_Expecter) Update(ctx interface{}, messageID interface{}, data interface{}) *MockMessageStorage_Update_Call {
	return &MockMessageStorage_Update_Call{Call: _e.mock.On("Update", ctx, messageID, data)}
}

func (_c *MockMessageStorage_Update_Call) Run(run func(ctx context.Context, messageID uint, data *entity.UpdateMessage)) *MockMessageStorage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*entity.UpdateMessage))
	})
	return _c
}

func (_c *MockMessageStorage_Update_Call) Return(_a0 error) *MockMessageStorage_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageStorage_Update_Call) RunAndReturn(run func(context.Context, uint, *entity.UpdateMessage) error) *MockMessageStorage_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageStorage creates a new instance of MockMessageStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageStorage {
	mock := &MockMessageStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
