// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "suscord/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockUserStorage is an autogenerated mock type for the UserStorage type
type MockUserStorage struct {
	mock.Mock
}

type MockUserStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserStorage) EXPECT() *MockUserStorage_Expecter {
	return &MockUserStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *MockUserStorage) Create(ctx context.Context, user *entity.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *MockUserStorage_Expecter) Create(ctx interface{}, user interface{}) *MockUserStorage_Create_Call {
	return &MockUserStorage_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserStorage_Create_Call) Run(run func(ctx context.Context, user *entity.User)) *MockUserStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.User))
	})
	return _c
}

func (_c *MockUserStorage_Create_Call) Return(_a0 error) *MockUserStorage_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserStorage_Create_Call) RunAndReturn(run func(context.Context, *entity.User) error) *MockUserStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockUserStorage) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockUserStorage_Expecter) Delete(ctx interface{}, id interface{}) *MockUserStorage_Delete_Call {
	return &MockUserStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserStorage_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockUserStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockUserStorage_Delete_Call) Return(_a0 error) *MockUserStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserStorage_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockUserStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockUserStorage) GetByID(ctx context.Context, id uint) (*entity.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStorage_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserStorage_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockUserStorage_Expecter) GetByID(ctx interface{}, id interface{}) *MockUserStorage_GetByID_Call {
	return &MockUserStorage_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserStorage_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockUserStorage_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockUserStorage_GetByID_Call) Return(_a0 *entity.User, _a1 error) *MockUserStorage_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStorage_GetByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.User, error)) *MockUserStorage_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function with given fields: ctx, username
func (_m *MockUserStorage) GetByUsername(ctx context.Context, username string) (*entity.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStorage_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockUserStorage_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserStorage_Expecter) GetByUsername(ctx interface{}, username interface{}) *MockUserStorage_GetByUsername_Call {
	return &MockUserStorage_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *MockUserStorage_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserStorage_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserStorage_GetByUsername_Call) Return(_a0 *entity.User, _a1 error) *MockUserStorage_GetByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStorage_GetByUsername_Call) RunAndReturn(run func(context.Context, string) (*entity.User, error)) *MockUserStorage_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: ctx, exceptUserID, username
func (_m *MockUserStorage) SearchUsers(ctx context.Context, exceptUserID uint, username string) ([]*entity.User, error) {
	ret := _m.Called(ctx, exceptUserID, username)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []*entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) ([]*entity.User, error)); ok {
		return rf(ctx, exceptUserID, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) []*entity.User); ok {
		r0 = rf(ctx, exceptUserID, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = rf(ctx, exceptUserID, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStorage_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockUserStorage_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - exceptUserID uint
//   - username string
func (_e *MockUserStorage_Expecter) SearchUsers(ctx interface{}, exceptUserID interface{}, username interface{}) *MockUserStorage_SearchUsers_Call {
	return &MockUserStorage_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, exceptUserID, username)}
}

func (_c *MockUserStorage_SearchUsers_Call) Run(run func(ctx context.Context, exceptUserID uint, username string)) *MockUserStorage_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *MockUserStorage_SearchUsers_Call) Return(_a0 []*entity.User, _a1 error) *MockUserStorage_SearchUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStorage_SearchUsers_Call) RunAndReturn(run func(context.Context, uint, string) ([]*entity.User, error)) *MockUserStorage_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, data
func (_m *MockUserStorage) Update(ctx context.Context, userID uint, data map[string]interface{}) error {
	ret := _m.Called(ctx, userID, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, map[string]interface{}) error); ok {
		r0 = rf(ctx, userID, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserStorage_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserStorage_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - data map[string]interface{}
func (_e *MockUserStorage_Expecter) Update(ctx interface{}, userID interface{}, data interface{}) *MockUserStorage_Update_Call {
	return &MockUserStorage_Update_Call{Call: _e.mock.On("Update", ctx, userID, data)}
}

func (_c *MockUserStorage_Update_Call) Run(run func(ctx context.Context, userID uint, data map[string]interface{})) *MockUserStorage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockUserStorage_Update_Call) Return(_a0 error) *MockUserStorage_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserStorage_Update_Call) RunAndReturn(run func(context.Context, uint, map[string]interface{}) error) *MockUserStorage_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserStorage creates a new instance of MockUserStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserStorage {
	mock := &MockUserStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
