// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "suscord/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockSessionStorage is an autogenerated mock type for the SessionStorage type
type MockSessionStorage struct {
	mock.Mock
}

type MockSessionStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStorage) EXPECT() *MockSessionStorage_Expecter {
	return &MockSessionStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID
func (_m *MockSessionStorage) Create(ctx context.Context, userID uint) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockSessionStorage_Expecter) Create(ctx interface{}, userID interface{}) *MockSessionStorage_Create_Call {
	return &MockSessionStorage_Create_Call{Call: _e.mock.On("Create", ctx, userID)}
}

func (_c *MockSessionStorage_Create_Call) Run(run func(ctx context.Context, userID uint)) *MockSessionStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSessionStorage_Create_Call) Return(_a0 string, _a1 error) *MockSessionStorage_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStorage_Create_Call) RunAndReturn(run func(context.Context, uint) (string, error)) *MockSessionStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, uuid
func (_m *MockSessionStorage) Delete(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockSessionStorage_Expecter) Delete(ctx interface{}, uuid interface{}) *MockSessionStorage_Delete_Call {
	return &MockSessionStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, uuid)}
}

func (_c *MockSessionStorage_Delete_Call) Run(run func(ctx context.Context, uuid string)) *MockSessionStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionStorage_Delete_Call) Return(_a0 error) *MockSessionStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStorage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockSessionStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUUID provides a mock function with given fields: ctx, uuid
func (_m *MockSessionStorage) GetByUUID(ctx context.Context, uuid string) (*entity.Session, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 *entity.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Session, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Session); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStorage_GetByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUID'
type MockSessionStorage_GetByUUID_Call struct {
	*mock.Call
}

// GetByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockSessionStorage_Expecter) GetByUUID(ctx interface{}, uuid interface{}) *MockSessionStorage_GetByUUID_Call {
	return &MockSessionStorage_GetByUUID_Call{Call: _e.mock.On("GetByUUID", ctx, uuid)}
}

func (_c *MockSessionStorage_GetByUUID_Call) Run(run func(ctx context.Context, uuid string)) *MockSessionStorage_GetByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionStorage_GetByUUID_Call) Return(_a0 *entity.Session, _a1 error) *MockSessionStorage_GetByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStorage_GetByUUID_Call) RunAndReturn(run func(context.Context, string) (*entity.Session, error)) *MockSessionStorage_GetByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockSessionStorage) GetByUserID(ctx context.Context, userID uint) (*entity.Session, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *entity.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Session, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Session); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStorage_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockSessionStorage_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockSessionStorage_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockSessionStorage_GetByUserID_Call {
	return &MockSessionStorage_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockSessionStorage_GetByUserID_Call) Run(run func(ctx context.Context, userID uint)) *MockSessionStorage_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSessionStorage_GetByUserID_Call) Return(_a0 *entity.Session, _a1 error) *MockSessionStorage_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStorage_GetByUserID_Call) RunAndReturn(run func(context.Context, uint) (*entity.Session, error)) *MockSessionStorage_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID
func (_m *MockSessionStorage) Update(ctx context.Context, userID uint) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStorage_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSessionStorage_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockSessionStorage_Expecter) Update(ctx interface{}, userID interface{}) *MockSessionStorage_Update_Call {
	return &MockSessionStorage_Update_Call{Call: _e.mock.On("Update", ctx, userID)}
}

func (_c *MockSessionStorage_Update_Call) Run(run func(ctx context.Context, userID uint)) *MockSessionStorage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSessionStorage_Update_Call) Return(_a0 string, _a1 error) *MockSessionStorage_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStorage_Update_Call) RunAndReturn(run func(context.Context, uint) (string, error)) *MockSessionStorage_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionStorage creates a new instance of MockSessionStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStorage {
	mock := &MockSessionStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
