// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	database "suscord/internal/domain/storage/database"

	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Attachment provides a mock function with no fields
func (_m *MockStorage) Attachment() database.AttachmentStorage {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Attachment")
	}

	var r0 database.AttachmentStorage
	if rf, ok := ret.Get(0).(func() database.AttachmentStorage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.AttachmentStorage)
		}
	}

	return r0
}

// MockStorage_Attachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attachment'
type MockStorage_Attachment_Call struct {
	*mock.Call
}

// Attachment is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Attachment() *MockStorage_Attachment_Call {
	return &MockStorage_Attachment_Call{Call: _e.mock.On("Attachment")}
}

func (_c *MockStorage_Attachment_Call) Run(run func()) *MockStorage_Attachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Attachment_Call) Return(_a0 database.AttachmentStorage) *MockStorage_Attachment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Attachment_Call) RunAndReturn(run func() database.AttachmentStorage) *MockStorage_Attachment_Call {
	_c.Call.Return(run)
	return _c
}

// Chat provides a mock function with no fields
func (_m *MockStorage) Chat() database.ChatStorage {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 database.ChatStorage
	if rf, ok := ret.Get(0).(func() database.ChatStorage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.ChatStorage)
		}
	}

	return r0
}

// MockStorage_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockStorage_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Chat() *MockStorage_Chat_Call {
	return &MockStorage_Chat_Call{Call: _e.mock.On("Chat")}
}

func (_c *MockStorage_Chat_Call) Run(run func()) *MockStorage_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Chat_Call) Return(_a0 database.ChatStorage) *MockStorage_Chat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Chat_Call) RunAndReturn(run func() database.ChatStorage) *MockStorage_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// ChatMember provides a mock function with no fields
func (_m *MockStorage) ChatMember() database.ChatMemberStorage {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChatMember")
	}

	var r0 database.ChatMemberStorage
	if rf, ok := ret.Get(0).(func() database.ChatMemberStorage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.ChatMemberStorage)
		}
	}

	return r0
}

// MockStorage_ChatMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatMember'
type MockStorage_ChatMember_Call struct {
	*mock.Call
}

// ChatMember is a helper method to define mock.On call
func (_e *MockStorage_Expecter) ChatMember() *MockStorage_ChatMember_Call {
	return &MockStorage_ChatMember_Call{Call: _e.mock.On("ChatMember")}
}

func (_c *MockStorage_ChatMember_Call) Run(run func()) *MockStorage_ChatMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_ChatMember_Call) Return(_a0 database.ChatMemberStorage) *MockStorage_ChatMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_ChatMember_Call) RunAndReturn(run func() database.ChatMemberStorage) *MockStorage_ChatMember_Call {
	_c.Call.Return(run)
	return _c
}

// Message provides a mock function with no fields
func (_m *MockStorage) Message() database.MessageStorage {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 database.MessageStorage
	if rf, ok := ret.Get(0).(func() database.MessageStorage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.MessageStorage)
		}
	}

	return r0
}

// MockStorage_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type MockStorage_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Message() *MockStorage_Message_Call {
	return &MockStorage_Message_Call{Call: _e.mock.On("Message")}
}

func (_c *MockStorage_Message_Call) Run(run func()) *MockStorage_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Message_Call) Return(_a0 database.MessageStorage) *MockStorage_Message_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Message_Call) RunAndReturn(run func() database.MessageStorage) *MockStorage_Message_Call {
	_c.Call.Return(run)
	return _c
}

// Session provides a mock function with no fields
func (_m *MockStorage) Session() database.SessionStorage {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Session")
	}

	var r0 database.SessionStorage
	if rf, ok := ret.Get(0).(func() database.SessionStorage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.SessionStorage)
		}
	}

	return r0
}

// MockStorage_Session_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Session'
type MockStorage_Session_Call struct {
	*mock.Call
}

// Session is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Session() *MockStorage_Session_Call {
	return &MockStorage_Session_Call{Call: _e.mock.On("Session")}
}

func (_c *MockStorage_Session_Call) Run(run func()) *MockStorage_Session_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Session_Call) Return(_a0 database.SessionStorage) *MockStorage_Session_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Session_Call) RunAndReturn(run func() database.SessionStorage) *MockStorage_Session_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function with no fields
func (_m *MockStorage) User() database.UserStorage {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 database.UserStorage
	if rf, ok := ret.Get(0).(func() database.UserStorage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.UserStorage)
		}
	}

	return r0
}

// MockStorage_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type MockStorage_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
func (_e *MockStorage_Expecter) User() *MockStorage_User_Call {
	return &MockStorage_User_Call{Call: _e.mock.On("User")}
}

func (_c *MockStorage_User_Call) Run(run func()) *MockStorage_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_User_Call) Return(_a0 database.UserStorage) *MockStorage_User_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_User_Call) RunAndReturn(run func() database.UserStorage) *MockStorage_User_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
