// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "suscord/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockChatStorage is an autogenerated mock type for the ChatStorage type
type MockChatStorage struct {
	mock.Mock
}

type MockChatStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatStorage) EXPECT() *MockChatStorage_Expecter {
	return &MockChatStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, data
func (_m *MockChatStorage) Create(ctx context.Context, data *entity.CreateChat) (uint, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.CreateChat) (uint, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.CreateChat) uint); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.CreateChat) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChatStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data *entity.CreateChat
func (_e *MockChatStorage_Expecter) Create(ctx interface{}, data interface{}) *MockChatStorage_Create_Call {
	return &MockChatStorage_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockChatStorage_Create_Call) Run(run func(ctx context.Context, data *entity.CreateChat)) *MockChatStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.CreateChat))
	})
	return _c
}

func (_c *MockChatStorage_Create_Call) Return(_a0 uint, _a1 error) *MockChatStorage_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatStorage_Create_Call) RunAndReturn(run func(context.Context, *entity.CreateChat) (uint, error)) *MockChatStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, chatID
func (_m *MockChatStorage) Delete(ctx context.Context, chatID uint) error {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, chatID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockChatStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uint
func (_e *MockChatStorage_Expecter) Delete(ctx interface{}, chatID interface{}) *MockChatStorage_Delete_Call {
	return &MockChatStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, chatID)}
}

func (_c *MockChatStorage_Delete_Call) Run(run func(ctx context.Context, chatID uint)) *MockChatStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockChatStorage_Delete_Call) Return(_a0 error) *MockChatStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatStorage_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockChatStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, chatID
func (_m *MockChatStorage) GetByID(ctx context.Context, chatID uint) (*entity.Chat, error) {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Chat, error)); ok {
		return rf(ctx, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Chat); ok {
		r0 = rf(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatStorage_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockChatStorage_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uint
func (_e *MockChatStorage_Expecter) GetByID(ctx interface{}, chatID interface{}) *MockChatStorage_GetByID_Call {
	return &MockChatStorage_GetByID_Call{Call: _e.mock.On("GetByID", ctx, chatID)}
}

func (_c *MockChatStorage_GetByID_Call) Run(run func(ctx context.Context, chatID uint)) *MockChatStorage_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockChatStorage_GetByID_Call) Return(_a0 *entity.Chat, _a1 error) *MockChatStorage_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatStorage_GetByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.Chat, error)) *MockChatStorage_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserChat provides a mock function with given fields: ctx, chatID, userID
func (_m *MockChatStorage) GetUserChat(ctx context.Context, chatID uint, userID uint) (*entity.Chat, error) {
	ret := _m.Called(ctx, chatID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserChat")
	}

	var r0 *entity.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*entity.Chat, error)); ok {
		return rf(ctx, chatID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *entity.Chat); ok {
		r0 = rf(ctx, chatID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, chatID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatStorage_GetUserChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserChat'
type MockChatStorage_GetUserChat_Call struct {
	*mock.Call
}

// GetUserChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uint
//   - userID uint
func (_e *MockChatStorage_Expecter) GetUserChat(ctx interface{}, chatID interface{}, userID interface{}) *MockChatStorage_GetUserChat_Call {
	return &MockChatStorage_GetUserChat_Call{Call: _e.mock.On("GetUserChat", ctx, chatID, userID)}
}

func (_c *MockChatStorage_GetUserChat_Call) Run(run func(ctx context.Context, chatID uint, userID uint)) *MockChatStorage_GetUserChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockChatStorage_GetUserChat_Call) Return(_a0 *entity.Chat, _a1 error) *MockChatStorage_GetUserChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatStorage_GetUserChat_Call) RunAndReturn(run func(context.Context, uint, uint) (*entity.Chat, error)) *MockChatStorage_GetUserChat_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserChats provides a mock function with given fields: ctx, userID
func (_m *MockChatStorage) GetUserChats(ctx context.Context, userID uint) ([]*entity.Chat, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserChats")
	}

	var r0 []*entity.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]*entity.Chat, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []*entity.Chat); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatStorage_GetUserChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserChats'
type MockChatStorage_GetUserChats_Call struct {
	*mock.Call
}

// GetUserChats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockChatStorage_Expecter) GetUserChats(ctx interface{}, userID interface{}) *MockChatStorage_GetUserChats_Call {
	return &MockChatStorage_GetUserChats_Call{Call: _e.mock.On("GetUserChats", ctx, userID)}
}

func (_c *MockChatStorage_GetUserChats_Call) Run(run func(ctx context.Context, userID uint)) *MockChatStorage_GetUserChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockChatStorage_GetUserChats_Call) Return(_a0 []*entity.Chat, _a1 error) *MockChatStorage_GetUserChats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatStorage_GetUserChats_Call) RunAndReturn(run func(context.Context, uint) ([]*entity.Chat, error)) *MockChatStorage_GetUserChats_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUserChats provides a mock function with given fields: ctx, userID, searchPattern
func (_m *MockChatStorage) SearchUserChats(ctx context.Context, userID uint, searchPattern string) ([]*entity.Chat, error) {
	ret := _m.Called(ctx, userID, searchPattern)

	if len(ret) == 0 {
		panic("no return value specified for SearchUserChats")
	}

	var r0 []*entity.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) ([]*entity.Chat, error)); ok {
		return rf(ctx, userID, searchPattern)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) []*entity.Chat); ok {
		r0 = rf(ctx, userID, searchPattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = rf(ctx, userID, searchPattern)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatStorage_SearchUserChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUserChats'
type MockChatStorage_SearchUserChats_Call struct {
	*mock.Call
}

// SearchUserChats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - searchPattern string
func (_e *MockChatStorage_Expecter) SearchUserChats(ctx interface{}, userID interface{}, searchPattern interface{}) *MockChatStorage_SearchUserChats_Call {
	return &MockChatStorage_SearchUserChats_Call{Call: _e.mock.On("SearchUserChats", ctx, userID, searchPattern)}
}

func (_c *MockChatStorage_SearchUserChats_Call) Run(run func(ctx context.Context, userID uint, searchPattern string)) *MockChatStorage_SearchUserChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *MockChatStorage_SearchUserChats_Call) Return(_a0 []*entity.Chat, _a1 error) *MockChatStorage_SearchUserChats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatStorage_SearchUserChats_Call) RunAndReturn(run func(context.Context, uint, string) ([]*entity.Chat, error)) *MockChatStorage_SearchUserChats_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, chatID, data
func (_m *MockChatStorage) Update(ctx context.Context, chatID uint, data *entity.UpdateChat) error {
	ret := _m.Called(ctx, chatID, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *entity.UpdateChat) error); ok {
		r0 = rf(ctx, chatID, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatStorage_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockChatStorage_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uint
//   - data *entity.UpdateChat
func (_e *MockChatStorage_Expecter) Update(ctx interface{}, chatID interface{}, data interface{}) *MockChatStorage_Update_Call {
	return &MockChatStorage_Update_Call{Call: _e.mock.On("Update", ctx, chatID, data)}
}

func (_c *MockChatStorage_Update_Call) Run(run func(ctx context.Context, chatID uint, data *entity.UpdateChat)) *MockChatStorage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*entity.UpdateChat))
	})
	return _c
}

func (_c *MockChatStorage_Update_Call) Return(_a0 error) *MockChatStorage_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatStorage_Update_Call) RunAndReturn(run func(context.Context, uint, *entity.UpdateChat) error) *MockChatStorage_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatStorage creates a new instance of MockChatStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatStorage {
	mock := &MockChatStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
