// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "suscord/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockChatMemberStorage is an autogenerated mock type for the ChatMemberStorage type
type MockChatMemberStorage struct {
	mock.Mock
}

type MockChatMemberStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatMemberStorage) EXPECT() *MockChatMemberStorage_Expecter {
	return &MockChatMemberStorage_Expecter{mock: &_m.Mock}
}

// AddUserToChat provides a mock function with given fields: ctx, userID, chatID
func (_m *MockChatMemberStorage) AddUserToChat(ctx context.Context, userID uint, chatID uint) error {
	ret := _m.Called(ctx, userID, chatID)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToChat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, userID, chatID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatMemberStorage_AddUserToChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToChat'
type MockChatMemberStorage_AddUserToChat_Call struct {
	*mock.Call
}

// AddUserToChat is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - chatID uint
func (_e *MockChatMemberStorage_Expecter) AddUserToChat(ctx interface{}, userID interface{}, chatID interface{}) *MockChatMemberStorage_AddUserToChat_Call {
	return &MockChatMemberStorage_AddUserToChat_Call{Call: _e.mock.On("AddUserToChat", ctx, userID, chatID)}
}

func (_c *MockChatMemberStorage_AddUserToChat_Call) Run(run func(ctx context.Context, userID uint, chatID uint)) *MockChatMemberStorage_AddUserToChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockChatMemberStorage_AddUserToChat_Call) Return(_a0 error) *MockChatMemberStorage_AddUserToChat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatMemberStorage_AddUserToChat_Call) RunAndReturn(run func(context.Context, uint, uint) error) *MockChatMemberStorage_AddUserToChat_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, chatID
func (_m *MockChatMemberStorage) Delete(ctx context.Context, userID uint, chatID uint) error {
	ret := _m.Called(ctx, userID, chatID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, userID, chatID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatMemberStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockChatMemberStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - chatID uint
func (_e *MockChatMemberStorage_Expecter) Delete(ctx interface{}, userID interface{}, chatID interface{}) *MockChatMemberStorage_Delete_Call {
	return &MockChatMemberStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, chatID)}
}

func (_c *MockChatMemberStorage_Delete_Call) Run(run func(ctx context.Context, userID uint, chatID uint)) *MockChatMemberStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockChatMemberStorage_Delete_Call) Return(_a0 error) *MockChatMemberStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatMemberStorage_Delete_Call) RunAndReturn(run func(context.Context, uint, uint) error) *MockChatMemberStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatMembers provides a mock function with given fields: ctx, chatID
func (_m *MockChatMemberStorage) GetChatMembers(ctx context.Context, chatID uint) ([]*entity.User, error) {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetChatMembers")
	}

	var r0 []*entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]*entity.User, error)); ok {
		return rf(ctx, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []*entity.User); ok {
		r0 = rf(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatMemberStorage_GetChatMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatMembers'
type MockChatMemberStorage_GetChatMembers_Call struct {
	*mock.Call
}

// GetChatMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uint
func (_e *MockChatMemberStorage_Expecter) GetChatMembers(ctx interface{}, chatID interface{}) *MockChatMemberStorage_GetChatMembers_Call {
	return &MockChatMemberStorage_GetChatMembers_Call{Call: _e.mock.On("GetChatMembers", ctx, chatID)}
}

func (_c *MockChatMemberStorage_GetChatMembers_Call) Run(run func(ctx context.Context, chatID uint)) *MockChatMemberStorage_GetChatMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockChatMemberStorage_GetChatMembers_Call) Return(_a0 []*entity.User, _a1 error) *MockChatMemberStorage_GetChatMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatMemberStorage_GetChatMembers_Call) RunAndReturn(run func(context.Context, uint) ([]*entity.User, error)) *MockChatMemberStorage_GetChatMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetNonMembers provides a mock function with given fields: ctx, chatID
func (_m *MockChatMemberStorage) GetNonMembers(ctx context.Context, chatID uint) ([]*entity.User, error) {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetNonMembers")
	}

	var r0 []*entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]*entity.User, error)); ok {
		return rf(ctx, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []*entity.User); ok {
		r0 = rf(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatMemberStorage_GetNonMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNonMembers'
type MockChatMemberStorage_GetNonMembers_Call struct {
	*mock.Call
}

// GetNonMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uint
func (_e *MockChatMemberStorage_Expecter) GetNonMembers(ctx interface{}, chatID interface{}) *MockChatMemberStorage_GetNonMembers_Call {
	return &MockChatMemberStorage_GetNonMembers_Call{Call: _e.mock.On("GetNonMembers", ctx, chatID)}
}

func (_c *MockChatMemberStorage_GetNonMembers_Call) Run(run func(ctx context.Context, chatID uint)) *MockChatMemberStorage_GetNonMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockChatMemberStorage_GetNonMembers_Call) Return(_a0 []*entity.User, _a1 error) *MockChatMemberStorage_GetNonMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatMemberStorage_GetNonMembers_Call) RunAndReturn(run func(context.Context, uint) ([]*entity.User, error)) *MockChatMemberStorage_GetNonMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateChatID provides a mock function with given fields: ctx, userID, friendID
func (_m *MockChatMemberStorage) GetPrivateChatID(ctx context.Context, userID uint, friendID uint) (uint, error) {
	ret := _m.Called(ctx, userID, friendID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateChatID")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (uint, error)); ok {
		return rf(ctx, userID, friendID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) uint); ok {
		r0 = rf(ctx, userID, friendID)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, userID, friendID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatMemberStorage_GetPrivateChatID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateChatID'
type MockChatMemberStorage_GetPrivateChatID_Call struct {
	*mock.Call
}

// GetPrivateChatID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - friendID uint
func (_e *MockChatMemberStorage_Expecter) GetPrivateChatID(ctx interface{}, userID interface{}, friendID interface{}) *MockChatMemberStorage_GetPrivateChatID_Call {
	return &MockChatMemberStorage_GetPrivateChatID_Call{Call: _e.mock.On("GetPrivateChatID", ctx, userID, friendID)}
}

func (_c *MockChatMemberStorage_GetPrivateChatID_Call) Run(run func(ctx context.Context, userID uint, friendID uint)) *MockChatMemberStorage_GetPrivateChatID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockChatMemberStorage_GetPrivateChatID_Call) Return(_a0 uint, _a1 error) *MockChatMemberStorage_GetPrivateChatID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatMemberStorage_GetPrivateChatID_Call) RunAndReturn(run func(context.Context, uint, uint) (uint, error)) *MockChatMemberStorage_GetPrivateChatID_Call {
	_c.Call.Return(run)
	return _c
}

// IsMemberOfChat provides a mock function with given fields: ctx, userID, chatID
func (_m *MockChatMemberStorage) IsMemberOfChat(ctx context.Context, userID uint, chatID uint) (bool, error) {
	ret := _m.Called(ctx, userID, chatID)

	if len(ret) == 0 {
		panic("no return value specified for IsMemberOfChat")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (bool, error)); ok {
		return rf(ctx, userID, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) bool); ok {
		r0 = rf(ctx, userID, chatID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, userID, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatMemberStorage_IsMemberOfChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMemberOfChat'
type MockChatMemberStorage_IsMemberOfChat_Call struct {
	*mock.Call
}

// IsMemberOfChat is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - chatID uint
func (_e *MockChatMemberStorage_Expecter) IsMemberOfChat(ctx interface{}, userID interface{}, chatID interface{}) *MockChatMemberStorage_IsMemberOfChat_Call {
	return &MockChatMemberStorage_IsMemberOfChat_Call{Call: _e.mock.On("IsMemberOfChat", ctx, userID, chatID)}
}

func (_c *MockChatMemberStorage_IsMemberOfChat_Call) Run(run func(ctx context.Context, userID uint, chatID uint)) *MockChatMemberStorage_IsMemberOfChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockChatMemberStorage_IsMemberOfChat_Call) Return(_a0 bool, _a1 error) *MockChatMemberStorage_IsMemberOfChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatMemberStorage_IsMemberOfChat_Call) RunAndReturn(run func(context.Context, uint, uint) (bool, error)) *MockChatMemberStorage_IsMemberOfChat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatMemberStorage creates a new instance of MockChatMemberStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatMemberStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatMemberStorage {
	mock := &MockChatMemberStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
