// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "suscord/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockAttachmentStorage is an autogenerated mock type for the AttachmentStorage type
type MockAttachmentStorage struct {
	mock.Mock
}

type MockAttachmentStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttachmentStorage) EXPECT() *MockAttachmentStorage_Expecter {
	return &MockAttachmentStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, messageID, data
func (_m *MockAttachmentStorage) Create(ctx context.Context, messageID uint, data *entity.CreateAttachment) (uint, error) {
	ret := _m.Called(ctx, messageID, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *entity.CreateAttachment) (uint, error)); ok {
		return rf(ctx, messageID, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *entity.CreateAttachment) uint); ok {
		r0 = rf(ctx, messageID, data)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *entity.CreateAttachment) error); ok {
		r1 = rf(ctx, messageID, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttachmentStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAttachmentStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID uint
//   - data *entity.CreateAttachment
func (_e *MockAttachmentStorage_Expecter) Create(ctx interface{}, messageID interface{}, data interface{}) *MockAttachmentStorage_Create_Call {
	return &MockAttachmentStorage_Create_Call{Call: _e.mock.On("Create", ctx, messageID, data)}
}

func (_c *MockAttachmentStorage_Create_Call) Run(run func(ctx context.Context, messageID uint, data *entity.CreateAttachment)) *MockAttachmentStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*entity.CreateAttachment))
	})
	return _c
}

func (_c *MockAttachmentStorage_Create_Call) Return(_a0 uint, _a1 error) *MockAttachmentStorage_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttachmentStorage_Create_Call) RunAndReturn(run func(context.Context, uint, *entity.CreateAttachment) (uint, error)) *MockAttachmentStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, attachmentID
func (_m *MockAttachmentStorage) Delete(ctx context.Context, attachmentID uint) error {
	ret := _m.Called(ctx, attachmentID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, attachmentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAttachmentStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAttachmentStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - attachmentID uint
func (_e *MockAttachmentStorage_Expecter) Delete(ctx interface{}, attachmentID interface{}) *MockAttachmentStorage_Delete_Call {
	return &MockAttachmentStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, attachmentID)}
}

func (_c *MockAttachmentStorage_Delete_Call) Run(run func(ctx context.Context, attachmentID uint)) *MockAttachmentStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAttachmentStorage_Delete_Call) Return(_a0 error) *MockAttachmentStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAttachmentStorage_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockAttachmentStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, attachmentID
func (_m *MockAttachmentStorage) GetByID(ctx context.Context, attachmentID uint) (*entity.Attachment, error) {
	ret := _m.Called(ctx, attachmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Attachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Attachment, error)); ok {
		return rf(ctx, attachmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Attachment); ok {
		r0 = rf(ctx, attachmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Attachment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, attachmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttachmentStorage_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAttachmentStorage_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - attachmentID uint
func (_e *MockAttachmentStorage_Expecter) GetByID(ctx interface{}, attachmentID interface{}) *MockAttachmentStorage_GetByID_Call {
	return &MockAttachmentStorage_GetByID_Call{Call: _e.mock.On("GetByID", ctx, attachmentID)}
}

func (_c *MockAttachmentStorage_GetByID_Call) Run(run func(ctx context.Context, attachmentID uint)) *MockAttachmentStorage_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAttachmentStorage_GetByID_Call) Return(_a0 *entity.Attachment, _a1 error) *MockAttachmentStorage_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttachmentStorage_GetByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.Attachment, error)) *MockAttachmentStorage_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByMessageID provides a mock function with given fields: ctx, messageID
func (_m *MockAttachmentStorage) GetByMessageID(ctx context.Context, messageID uint) ([]*entity.Attachment, error) {
	ret := _m.Called(ctx, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetByMessageID")
	}

	var r0 []*entity.Attachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]*entity.Attachment, error)); ok {
		return rf(ctx, messageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []*entity.Attachment); ok {
		r0 = rf(ctx, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Attachment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, messageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttachmentStorage_GetByMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByMessageID'
type MockAttachmentStorage_GetByMessageID_Call struct {
	*mock.Call
}

// GetByMessageID is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID uint
func (_e *MockAttachmentStorage_Expecter) GetByMessageID(ctx interface{}, messageID interface{}) *MockAttachmentStorage_GetByMessageID_Call {
	return &MockAttachmentStorage_GetByMessageID_Call{Call: _e.mock.On("GetByMessageID", ctx, messageID)}
}

func (_c *MockAttachmentStorage_GetByMessageID_Call) Run(run func(ctx context.Context, messageID uint)) *MockAttachmentStorage_GetByMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAttachmentStorage_GetByMessageID_Call) Return(_a0 []*entity.Attachment, _a1 error) *MockAttachmentStorage_GetByMessageID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttachmentStorage_GetByMessageID_Call) RunAndReturn(run func(context.Context, uint) ([]*entity.Attachment, error)) *MockAttachmentStorage_GetByMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// IsOwner provides a mock function with given fields: ctx, userID, attachmentID
func (_m *MockAttachmentStorage) IsOwner(ctx context.Context, userID uint, attachmentID uint) (bool, error) {
	ret := _m.Called(ctx, userID, attachmentID)

	if len(ret) == 0 {
		panic("no return value specified for IsOwner")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (bool, error)); ok {
		return rf(ctx, userID, attachmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) bool); ok {
		r0 = rf(ctx, userID, attachmentID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, userID, attachmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttachmentStorage_IsOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOwner'
type MockAttachmentStorage_IsOwner_Call struct {
	*mock.Call
}

// IsOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - attachmentID uint
func (_e *MockAttachmentStorage_Expecter) IsOwner(ctx interface{}, userID interface{}, attachmentID interface{}) *MockAttachmentStorage_IsOwner_Call {
	return &MockAttachmentStorage_IsOwner_Call{Call: _e.mock.On("IsOwner", ctx, userID, attachmentID)}
}

func (_c *MockAttachmentStorage_IsOwner_Call) Run(run func(ctx context.Context, userID uint, attachmentID uint)) *MockAttachmentStorage_IsOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockAttachmentStorage_IsOwner_Call) Return(_a0 bool, _a1 error) *MockAttachmentStorage_IsOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttachmentStorage_IsOwner_Call) RunAndReturn(run func(context.Context, uint, uint) (bool, error)) *MockAttachmentStorage_IsOwner_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAttachmentStorage creates a new instance of MockAttachmentStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttachmentStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttachmentStorage {
	mock := &MockAttachmentStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
