// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	message "suscord/internal/domain/broker/message"

	mock "github.com/stretchr/testify/mock"
)

// MockBroker is an autogenerated mock type for the Broker type
type MockBroker struct {
	mock.Mock
}

type MockBroker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBroker) EXPECT() *MockBroker_Expecter {
	return &MockBroker_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, _a1
func (_m *MockBroker) Publish(ctx context.Context, _a1 message.BrokerMessage) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, message.BrokerMessage) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBroker_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockBroker_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 message.BrokerMessage
func (_e *MockBroker_Expecter) Publish(ctx interface{}, _a1 interface{}) *MockBroker_Publish_Call {
	return &MockBroker_Publish_Call{Call: _e.mock.On("Publish", ctx, _a1)}
}

func (_c *MockBroker_Publish_Call) Run(run func(ctx context.Context, _a1 message.BrokerMessage)) *MockBroker_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(message.BrokerMessage))
	})
	return _c
}

func (_c *MockBroker_Publish_Call) Return(_a0 error) *MockBroker_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBroker_Publish_Call) RunAndReturn(run func(context.Context, message.BrokerMessage) error) *MockBroker_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBroker creates a new instance of MockBroker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBroker {
	mock := &MockBroker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
